"""two

Revision ID: c2974fb0197b
Revises: 
Create Date: 2023-05-31 17:16:52.819281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2974fb0197b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, cache=1), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('systemusers',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, cache=1), nullable=False),
    sa.Column('name', sa.VARCHAR(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messagecontexts',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, cache=1), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('expire', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['systemusers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegramusers',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, cache=1), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('telegram_user_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['systemusers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersubscriptions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, cache=1), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('level', sa.Enum('free', 'low', 'medium', 'unlimited', name='sublevelenum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['systemusers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialogmessages',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, cache=1), nullable=False),
    sa.Column('context_id', sa.BIGINT(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='role'), nullable=False),
    sa.Column('text', sa.VARCHAR(length=3000), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['messagecontexts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('limits',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, cache=1), nullable=False),
    sa.Column('subscription_id', sa.BIGINT(), nullable=False),
    sa.Column('limit', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['usersubscriptions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rateexpires',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, cache=1), nullable=False),
    sa.Column('subscription_id', sa.BIGINT(), nullable=False),
    sa.Column('expire_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['usersubscriptions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('limitexpires',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, cache=1), nullable=False),
    sa.Column('limit_id', sa.BIGINT(), nullable=False),
    sa.Column('expire_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['limit_id'], ['limits.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replys',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, cache=1), nullable=False),
    sa.Column('message_id', sa.BIGINT(), nullable=False),
    sa.Column('reply_to', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['dialogmessages.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegrammessages',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, cache=1), nullable=False),
    sa.Column('message_id', sa.BIGINT(), nullable=False),
    sa.Column('telegram_message_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['dialogmessages.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegrammessages')
    op.drop_table('replys')
    op.drop_table('limitexpires')
    op.drop_table('rateexpires')
    op.drop_table('limits')
    op.drop_table('dialogmessages')
    op.drop_table('usersubscriptions')
    op.drop_table('telegramusers')
    op.drop_table('messagecontexts')
    op.drop_table('systemusers')
    op.drop_table('channels')
    # ### end Alembic commands ###
    sa.Enum(name="sublevelenum").drop(op.get_bind())
    sa.Enum(name="role").drop(op.get_bind())
